-- =====================================================================
--  Currency  -  150 satir
--
--  URETILMIS DOSYA. Elle duzenlemeyin.
--  Kaynak: db/generate-seed.mjs   ->   node db/generate-seed.mjs
--
--  CurrencyNumericCode ISO 4217'den geliyor (db/currency-codes.json).
--  Kolon varchar(3) oldugu icin bastaki sifirlar korunuyor: '008'.
-- =====================================================================

insert into "SystemAdmin"."Currency"
    ("CurrencyAlphaCode", "CurrencyNumericCode", "CurrencyName", "RecordStatus")
values
    ('AWG', '533', 'Aruban Florin', 1),
    ('AFN', '971', 'Afghani', 1),
    ('AOA', '973', 'Kwanza', 1),
    ('XCD', '951', 'East Caribbean Dollar', 1),
    ('EUR', '978', 'Euro', 1),
    ('ALL', '008', 'Lek', 1),
    ('AED', '784', 'UAE Dirham', 1),
    ('ARS', '032', 'Argentine Peso', 1),
    ('AMD', '051', 'Armenian Dram', 1),
    ('USD', '840', 'US Dollar', 1),
    ('AUD', '036', 'Australian Dollar', 1),
    ('AZN', '944', 'Azerbaijan Manat', 1),
    ('BIF', '108', 'Burundi Franc', 1),
    ('XOF', '952', 'CFA Franc BCEAO', 1),
    ('BDT', '050', 'Taka', 1),
    ('BHD', '048', 'Bahraini Dinar', 1),
    ('BSD', '044', 'Bahamian Dollar', 1),
    ('BAM', '977', 'Convertible Mark', 1),
    ('GBP', '826', 'Pound Sterling', 1),
    ('BYN', '933', 'Belarusian Ruble', 1),
    ('BZD', '084', 'Belize Dollar', 1),
    ('BMD', '060', 'Bermudian Dollar', 1),
    ('BOB', '068', 'Boliviano', 1),
    ('BRL', '986', 'Brazilian Real', 1),
    ('BBD', '052', 'Barbados Dollar', 1),
    ('BND', '096', 'Brunei Dollar', 1),
    ('BTN', '064', 'Ngultrum', 1),
    ('BWP', '072', 'Pula', 1),
    ('XAF', '950', 'CFA Franc BEAC', 1),
    ('CAD', '124', 'Canadian Dollar', 1),
    ('CHF', '756', 'Swiss Franc', 1),
    ('CLP', '152', 'Chilean Peso', 1),
    ('CNY', '156', 'Yuan Renminbi', 1),
    ('CDF', '976', 'Congolese Franc', 1),
    ('COP', '170', 'Colombian Peso', 1),
    ('KMF', '174', 'Comorian Franc', 1),
    ('CVE', '132', 'Cabo Verde Escudo', 1),
    ('CRC', '188', 'Costa Rican Colon', 1),
    ('KYD', '136', 'Cayman Islands Dollar', 1),
    ('CZK', '203', 'Czech Koruna', 1),
    ('DJF', '262', 'Djibouti Franc', 1),
    ('DKK', '208', 'Danish Krone', 1),
    ('DOP', '214', 'Dominican Peso', 1),
    ('DZD', '012', 'Algerian Dinar', 1),
    ('EGP', '818', 'Egyptian Pound', 1),
    ('ERN', '232', 'Nakfa', 1),
    ('ETB', '230', 'Ethiopian Birr', 1),
    ('FJD', '242', 'Fiji Dollar', 1),
    ('FKP', '238', 'Falkland Islands Pound', 1),
    ('GEL', '981', 'Lari', 1),
    ('GHS', '936', 'Ghana Cedi', 1),
    ('GIP', '292', 'Gibraltar Pound', 1),
    ('GNF', '324', 'Guinean Franc', 1),
    ('GMD', '270', 'Dalasi', 1),
    ('GTQ', '320', 'Quetzal', 1),
    ('GYD', '328', 'Guyana Dollar', 1),
    ('HKD', '344', 'Hong Kong Dollar', 1),
    ('HNL', '340', 'Lempira', 1),
    ('HTG', '332', 'Gourde', 1),
    ('HUF', '348', 'Forint', 1),
    ('IDR', '360', 'Rupiah', 1),
    ('INR', '356', 'Indian Rupee', 1),
    ('IRR', '364', 'Iranian Rial', 1),
    ('IQD', '368', 'Iraqi Dinar', 1),
    ('ISK', '352', 'Iceland Krona', 1),
    ('ILS', '376', 'New Israeli Sheqel', 1),
    ('JMD', '388', 'Jamaican Dollar', 1),
    ('JOD', '400', 'Jordanian Dinar', 1),
    ('JPY', '392', 'Yen', 1),
    ('KZT', '398', 'Tenge', 1),
    ('KES', '404', 'Kenyan Shilling', 1),
    ('KGS', '417', 'Som', 1),
    ('KHR', '116', 'Riel', 1),
    ('KRW', '410', 'Won', 1),
    ('KWD', '414', 'Kuwaiti Dinar', 1),
    ('LAK', '418', 'Lao Kip', 1),
    ('LBP', '422', 'Lebanese Pound', 1),
    ('LRD', '430', 'Liberian Dollar', 1),
    ('LYD', '434', 'Libyan Dinar', 1),
    ('LKR', '144', 'Sri Lanka Rupee', 1),
    ('LSL', '426', 'Loti', 1),
    ('MOP', '446', 'Pataca', 1),
    ('MAD', '504', 'Moroccan Dirham', 1),
    ('MDL', '498', 'Moldovan Leu', 1),
    ('MGA', '969', 'Malagasy Ariary', 1),
    ('MVR', '462', 'Rufiyaa', 1),
    ('MXN', '484', 'Mexican Peso', 1),
    ('MKD', '807', 'Denar', 1),
    ('MMK', '104', 'Kyat', 1),
    ('MNT', '496', 'Tugrik', 1),
    ('MZN', '943', 'Mozambique Metical', 1),
    ('MRU', '929', 'Ouguiya', 1),
    ('MUR', '480', 'Mauritius Rupee', 1),
    ('MWK', '454', 'Malawi Kwacha', 1),
    ('MYR', '458', 'Malaysian Ringgit', 1),
    ('NAD', '516', 'Namibia Dollar', 1),
    ('XPF', '953', 'CFP Franc', 1),
    ('NGN', '566', 'Naira', 1),
    ('NIO', '558', 'Cordoba Oro', 1),
    ('NZD', '554', 'New Zealand Dollar', 1),
    ('NOK', '578', 'Norwegian Krone', 1),
    ('NPR', '524', 'Nepalese Rupee', 1),
    ('OMR', '512', 'Rial Omani', 1),
    ('PKR', '586', 'Pakistan Rupee', 1),
    ('PAB', '590', 'Balboa', 1),
    ('PEN', '604', 'Sol', 1),
    ('PHP', '608', 'Philippine Peso', 1),
    ('PGK', '598', 'Kina', 1),
    ('PLN', '985', 'Zloty', 1),
    ('KPW', '408', 'North Korean Won', 1),
    ('PYG', '600', 'Guarani', 1),
    ('QAR', '634', 'Qatari Rial', 1),
    ('RON', '946', 'Romanian Leu', 1),
    ('RUB', '643', 'Russian Ruble', 1),
    ('RWF', '646', 'Rwanda Franc', 1),
    ('SAR', '682', 'Saudi Riyal', 1),
    ('SDG', '938', 'Sudanese Pound', 1),
    ('SGD', '702', 'Singapore Dollar', 1),
    ('SHP', '654', 'Saint Helena Pound', 1),
    ('SBD', '090', 'Solomon Islands Dollar', 1),
    ('SLE', '925', 'Leone', 1),
    ('SOS', '706', 'Somali Shilling', 1),
    ('RSD', '941', 'Serbian Dinar', 1),
    ('SSP', '728', 'South Sudanese Pound', 1),
    ('STN', '930', 'Dobra', 1),
    ('SRD', '968', 'Surinam Dollar', 1),
    ('SEK', '752', 'Swedish Krona', 1),
    ('SZL', '748', 'Lilangeni', 1),
    ('SCR', '690', 'Seychelles Rupee', 1),
    ('SYP', '760', 'Syrian Pound', 1),
    ('THB', '764', 'Baht', 1),
    ('TJS', '972', 'Somoni', 1),
    ('TMT', '934', 'Turkmenistan New Manat', 1),
    ('TOP', '776', 'Pa’anga', 1),
    ('TTD', '780', 'Trinidad and Tobago Dollar', 1),
    ('TND', '788', 'Tunisian Dinar', 1),
    ('TRY', '949', 'Turkish Lira', 1),
    ('TWD', '901', 'New Taiwan Dollar', 1),
    ('TZS', '834', 'Tanzanian Shilling', 1),
    ('UGX', '800', 'Uganda Shilling', 1),
    ('UAH', '980', 'Hryvnia', 1),
    ('UYU', '858', 'Peso Uruguayo', 1),
    ('UZS', '860', 'Uzbekistan Sum', 1),
    ('VES', '928', 'Bolívar Soberano', 1),
    ('VND', '704', 'Dong', 1),
    ('VUV', '548', 'Vatu', 1),
    ('WST', '882', 'Tala', 1),
    ('YER', '886', 'Yemeni Rial', 1),
    ('ZAR', '710', 'Rand', 1),
    ('ZMW', '967', 'Zambian Kwacha', 1);
